-- Add payment gateway settings to company_info table
ALTER TABLE public.company_info
ADD COLUMN IF NOT EXISTS payment_gateway_primary text DEFAULT 'mercadopago',
ADD COLUMN IF NOT EXISTS mercadopago_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS mercadopago_public_key text,
ADD COLUMN IF NOT EXISTS mercadopago_access_token text,
ADD COLUMN IF NOT EXISTS mercadopago_sandbox boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS efi_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS efi_client_id text,
ADD COLUMN IF NOT EXISTS efi_client_secret text,
ADD COLUMN IF NOT EXISTS efi_sandbox boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS efi_pix_key text,
ADD COLUMN IF NOT EXISTS pagseguro_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS pagseguro_email text,
ADD COLUMN IF NOT EXISTS pagseguro_token text,
ADD COLUMN IF NOT EXISTS pagseguro_sandbox boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS stripe_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS stripe_public_key text,
ADD COLUMN IF NOT EXISTS stripe_secret_key text,
ADD COLUMN IF NOT EXISTS stripe_sandbox boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS asaas_enabled boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS asaas_api_key text,
ADD COLUMN IF NOT EXISTS asaas_sandbox boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS payment_methods_enabled text[] DEFAULT ARRAY['pix', 'credit_card', 'boleto']::text[],
ADD COLUMN IF NOT EXISTS pix_discount_percent numeric DEFAULT 5,
ADD COLUMN IF NOT EXISTS boleto_extra_days integer DEFAULT 3,
ADD COLUMN IF NOT EXISTS max_installments integer DEFAULT 12,
ADD COLUMN IF NOT EXISTS min_installment_value numeric DEFAULT 50;